nrf_security: Make sure platform_cc310 is referenced only when defined.
Undefined reference to platform_cc310 when a project is built with
nrf9160dk_nrf9160ns, hence CMake compilation error. An if-clause is
used to protect such case.

Signed-off-by: PK Chan <pak.kee.chan@nordicsemi.no>